document.addEventListener('DOMContentLoaded',function(){var params=new URLSearchParams(window.location.search);params.set('external_source',window.location.pathname.replace(/^\//,'').replace(/\.html$/,''));var qs=params.toString();document.querySelectorAll('a[href]').forEach(function(link){var href=link.getAttribute('href');if(!href||href.charAt(0)==='#'||href.indexOf('mailto:')===0||href.indexOf('tel:')===0||href.indexOf('javascript:')===0)return;link.href=href.indexOf('?')>-1?href+'&'+qs:href+'?'+qs});});
function toggleQa(btn){var qa=btn.closest('.qa');var open=qa.classList.contains('open');document.querySelectorAll('.qa.open').forEach(function(o){o.classList.remove('open');o.querySelector('.qa-a').style.maxHeight=null});if(!open){qa.classList.add('open');var a=qa.querySelector('.qa-a');a.style.maxHeight=a.scrollHeight+'px'}}
/* live "people starting today" counter – ticks up by 1 every 4–9s */
(function(){var el=document.getElementById('liveCount');if(!el)return;var n=1217;function fmt(x){return x.toLocaleString('en-US')}el.textContent=fmt(n);function tick(){n+=1;el.textContent=fmt(n);setTimeout(tick,4000+Math.random()*5000)}setTimeout(tick,4000+Math.random()*4000)})();
(function(){var els=document.querySelectorAll('.appear');if(!('IntersectionObserver'in window)){els.forEach(function(e){e.classList.add('is-visible')});return}var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting){x.target.classList.add('is-visible');io.unobserve(x.target)}})},{threshold:.12,rootMargin:'0px 0px -8% 0px'});els.forEach(function(e){io.observe(e)})})();
(function(){var sec=document.getElementById('niche'),orb=document.getElementById('glowOrb');if(!sec||!orb)return;sec.addEventListener('pointermove',function(e){var r=sec.getBoundingClientRect();orb.style.left=(e.clientX-r.left)+'px';orb.style.top=(e.clientY-r.top)+'px';orb.style.opacity='1'});sec.addEventListener('pointerleave',function(){orb.style.opacity='0'})})();
/* hero mockup – phase 1: horizontal slider (slide 1->2->3), phase 2: very smooth scroll to Most Popular -> Fresh Off the Press, loop */
(function(){var vp=document.querySelector('.hp-mock-vp');if(!vp)return;var track=vp.querySelector('.hp-mock-track');var row=track.querySelector('.hp-slider-row');var pops=track.querySelectorAll(':scope > img');if(!row||!pops.length)return;if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
var steps=[{x:0,y:'top',td:1.4,d:1800,ri:1},{x:-33.3333,y:'top',td:0,d:1700},{x:-66.6666,y:'top',td:0,d:2000},{x:-66.6666,y:'pop',td:2.2,d:2600},{x:-66.6666,y:'end',td:2.8,d:3300}];
function maxY(){return Math.max(0,track.scrollHeight-vp.clientHeight)}
function yval(k){if(k==='top')return 0;if(k==='pop')return Math.min(maxY(),pops[0].offsetTop);return maxY()}
var i=0;function apply(){var st=steps[i];row.style.transition=st.ri?'none':'transform .9s cubic-bezier(.5,0,.2,1)';row.style.transform='translateX('+st.x+'%)';track.style.transition='transform '+st.td+'s cubic-bezier(.45,0,.18,1)';track.style.transform='translateY(-'+yval(st.y)+'px)';i=(i+1)%steps.length;setTimeout(apply,st.d)}
function start(){setTimeout(apply,1000)}if(document.readyState==='complete')start();else window.addEventListener('load',start)})();
/* hero mockup height: bottom edge ends level with the CTA row (desktop); slider fills the viewport */
(function(){var vp=document.querySelector('.hp-mock-vp'),eb=document.querySelector('.hp-eyebrow'),cta=document.querySelector('.hp-cta-row');if(!vp||!eb||!cta)return;function fit(){if(window.matchMedia('(min-width:981px)').matches){var h=Math.round(cta.getBoundingClientRect().bottom-eb.getBoundingClientRect().top);if(h>140)vp.style.height=h+'px'}else{vp.style.height=''}}if(document.readyState==='complete')fit();else window.addEventListener('load',fit);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(fit);var t;window.addEventListener('resize',function(){clearTimeout(t);t=setTimeout(fit,120)})})();
/* freebasic product card: reveal 1s after the section first scrolls into view */
(function(){var sec=document.querySelector('.freebasic-section'),ov=document.querySelector('.fb-overlay');if(!sec||!ov)return;function steps(){setTimeout(function(){ov.classList.add('s1')},1000);setTimeout(function(){ov.classList.add('s2')},2000);setTimeout(function(){ov.classList.add('s3')},2500);setTimeout(function(){ov.classList.add('s4')},3000)}if(!('IntersectionObserver'in window)){ov.classList.add('s1','s2','s3','s4');return}var done=false;var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting&&!done){done=true;io.disconnect();steps()}})},{threshold:.25});io.observe(sec)})();
/* bento cards: on touch (no hover) auto-cycle the image reveal like the reference */
(function(){if(window.matchMedia&&(window.matchMedia('(hover:hover)').matches||window.matchMedia('(prefers-reduced-motion: reduce)').matches))return;var sec=document.querySelector('.bento-sec');if(!sec)return;var cards=sec.querySelectorAll('.bcard');if(!cards.length)return;var i=-1,timer=null;function clear(){for(var k=0;k<cards.length;k++)cards[k].classList.remove('demo-on')}function step(){clear();i=(i+1)%cards.length;cards[i].classList.add('demo-on')}function start(){if(timer)return;step();timer=setInterval(step,1800)}function stop(){if(timer){clearInterval(timer);timer=null}clear()}if(!('IntersectionObserver'in window)){start();return}var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting){start()}else{stop()}})},{threshold:.3});io.observe(sec)})();
/* testimonials carousel: infinite seamless loop (clones), peek both sides, dots + drag (mouse/touch), autoplay left */
(function(){var slider=document.querySelector('.tslider');if(!slider)return;var vp=slider.querySelector('.tslider-viewport'),track=slider.querySelector('.tslider-track');var dots=[].slice.call(slider.querySelectorAll('.tdot'));var real=[].slice.call(track.children);var n=real.length;if(!vp||!track||n<2)return;var reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;var fc=real[0].cloneNode(true),lc=real[n-1].cloneNode(true);fc.setAttribute('aria-hidden','true');lc.setAttribute('aria-hidden','true');track.insertBefore(lc,real[0]);track.appendChild(fc);var slides=[].slice.call(track.children);var pos=1,animating=false,timer=null,dur=560,hovering=false,dragging=false,startX=0,baseX=0,dx=0;function sw(){return slides[0].getBoundingClientRect().width}function gap(){return parseFloat(getComputedStyle(track).columnGap)||0}function base(){return vp.clientWidth/2-(pos*(sw()+gap())+sw()/2)}function setAnim(on){track.style.transition=on?'transform .56s cubic-bezier(.22,1,.36,1)':'none';for(var i=0;i<slides.length;i++)slides[i].style.transition=on?'':'none'}function render(){track.style.transform='translateX('+base()+'px)';var ri=((pos-1)%n+n)%n;for(var i=0;i<slides.length;i++)slides[i].classList.toggle('is-active',i===pos);dots.forEach(function(d,i){d.classList.toggle('is-active',i===ri)})}function place(anim){setAnim(anim);render()}function settle(){if(pos===n+1)pos=1;else if(pos===0)pos=n;place(false);animating=false}function move(d){if(animating)return;animating=true;pos+=d;place(true);setTimeout(settle,dur+30)}function jump(ri){if(animating)return;var t=ri+1;if(t===pos)return;animating=true;pos=t;place(true);setTimeout(function(){animating=false},dur+30)}function stop(){if(timer){clearInterval(timer);timer=null}}function play(){if(reduce||timer||hovering||dragging)return;timer=setInterval(function(){move(1)},4200)}dots.forEach(function(d,i){d.addEventListener('click',function(){jump(i);stop();play()})});slider.addEventListener('mouseenter',function(){hovering=true;stop()});slider.addEventListener('mouseleave',function(){hovering=false;play()});vp.addEventListener('pointerdown',function(e){if(animating)return;dragging=true;startX=e.clientX;dx=0;baseX=base();setAnim(false);stop();if(vp.setPointerCapture){try{vp.setPointerCapture(e.pointerId)}catch(_){}}vp.classList.add('is-drag')});vp.addEventListener('pointermove',function(e){if(!dragging)return;dx=e.clientX-startX;track.style.transform='translateX('+(baseX+dx)+'px)'});function endDrag(){if(!dragging)return;dragging=false;vp.classList.remove('is-drag');var th=Math.min(80,sw()*0.16);if(dx<-th)move(1);else if(dx>th)move(-1);else place(true);dx=0;play()}vp.addEventListener('pointerup',endDrag);vp.addEventListener('pointercancel',endDrag);var rt;window.addEventListener('resize',function(){clearTimeout(rt);rt=setTimeout(function(){place(false)},120)});if(document.fonts&&document.fonts.ready)document.fonts.ready.then(function(){place(false)});place(false);play()})();
/* sienna video: autoplay once on first view, then manual; pause when out of view; center play/pause button */
(function(){var sec=document.querySelector('.sienna-sec');if(!sec)return;var v=sec.querySelector('.sienna-bg'),btn=sec.querySelector('.sienna-play');if(!v||!btn)return;var started=false;function sync(){var playing=started&&!v.paused&&!v.ended;btn.classList.toggle('is-playing',playing);btn.setAttribute('aria-label',!started?'Play video with sound':(playing?'Pause video':'Play video'))}v.addEventListener('play',sync);v.addEventListener('pause',sync);v.addEventListener('ended',sync);btn.addEventListener('click',function(){if(!started){started=true;v.muted=false;try{v.currentTime=0}catch(_){}var p=v.play();if(p&&p.catch)p.catch(function(){});sync();return}if(v.paused||v.ended){var p=v.play();if(p&&p.catch)p.catch(function(){})}else{v.pause()}});var auto=false;if('IntersectionObserver'in window){var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting){if(!auto){auto=true;var p=v.play();if(p&&p.catch)p.catch(function(){})}}else{v.pause()}})},{threshold:.4});io.observe(sec)}sync()})();
