document.addEventListener('DOMContentLoaded',function(){var params=new URLSearchParams(window.location.search);params.set('external_source',window.location.pathname.replace(/^\//,'').replace(/\.html$/,''));var qs=params.toString();document.querySelectorAll('a[href]').forEach(function(link){var href=link.getAttribute('href');if(!href||href.charAt(0)==='#'||href.indexOf('mailto:')===0||href.indexOf('tel:')===0||href.indexOf('javascript:')===0)return;link.href=href.indexOf('?')>-1?href+'&'+qs:href+'?'+qs});});
function toggleQa(btn){var qa=btn.closest('.qa');var open=qa.classList.contains('open');document.querySelectorAll('.qa.open').forEach(function(o){o.classList.remove('open');o.querySelector('.qa-a').style.maxHeight=null});if(!open){qa.classList.add('open');var a=qa.querySelector('.qa-a');a.style.maxHeight=a.scrollHeight+'px'}}
/* live "people starting today" counter – ticks up by 1 every 4–9s */
(function(){var el=document.getElementById('liveCount');if(!el)return;var n=1217;function fmt(x){return x.toLocaleString('en-US')}el.textContent=fmt(n);function tick(){n+=1;el.textContent=fmt(n);setTimeout(tick,4000+Math.random()*5000)}setTimeout(tick,4000+Math.random()*4000)})();
(function(){var els=document.querySelectorAll('.appear');if(!('IntersectionObserver'in window)){els.forEach(function(e){e.classList.add('is-visible')});return}var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting){x.target.classList.add('is-visible');io.unobserve(x.target)}})},{threshold:.12,rootMargin:'0px 0px -8% 0px'});els.forEach(function(e){io.observe(e)})})();
(function(){var sec=document.getElementById('niche'),orb=document.getElementById('glowOrb');if(!sec||!orb)return;sec.addEventListener('pointermove',function(e){var r=sec.getBoundingClientRect();orb.style.left=(e.clientX-r.left)+'px';orb.style.top=(e.clientY-r.top)+'px';orb.style.opacity='1'});sec.addEventListener('pointerleave',function(){orb.style.opacity='0'})})();
/* hero mockup – phase 1: horizontal slider (slide 1->2->3), phase 2: very smooth scroll to Most Popular -> Fresh Off the Press, loop */
(function(){var vp=document.querySelector('.hp-mock-vp');if(!vp)return;var track=vp.querySelector('.hp-mock-track');var row=track.querySelector('.hp-slider-row');var pops=track.querySelectorAll(':scope > img');if(!row||!pops.length)return;if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
var steps=[{x:0,y:'top',td:1.4,d:1800,ri:1},{x:-33.3333,y:'top',td:0,d:1700},{x:-66.6666,y:'top',td:0,d:2000},{x:-66.6666,y:'pop',td:2.2,d:2600},{x:-66.6666,y:'end',td:2.8,d:3300}];
function maxY(){return Math.max(0,track.scrollHeight-vp.clientHeight)}
function yval(k){if(k==='top')return 0;if(k==='pop')return Math.min(maxY(),pops[0].offsetTop);return maxY()}
var i=0;function apply(){var st=steps[i];row.style.transition=st.ri?'none':'transform .9s cubic-bezier(.5,0,.2,1)';row.style.transform='translateX('+st.x+'%)';track.style.transition='transform '+st.td+'s cubic-bezier(.45,0,.18,1)';track.style.transform='translateY(-'+yval(st.y)+'px)';i=(i+1)%steps.length;setTimeout(apply,st.d)}
function start(){setTimeout(apply,1000)}if(document.readyState==='complete')start();else window.addEventListener('load',start)})();
/* hero mockup height: bottom edge ends level with the CTA row (desktop); slider fills the viewport */
(function(){var vp=document.querySelector('.hp-mock-vp'),eb=document.querySelector('.hp-eyebrow'),cta=document.querySelector('.hp-cta-row');if(!vp||!eb||!cta)return;function fit(){if(window.matchMedia('(min-width:981px)').matches){var h=Math.round(cta.getBoundingClientRect().bottom-eb.getBoundingClientRect().top);if(h>140)vp.style.height=h+'px'}else{vp.style.height=''}}if(document.readyState==='complete')fit();else window.addEventListener('load',fit);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(fit);var t;window.addEventListener('resize',function(){clearTimeout(t);t=setTimeout(fit,120)})})();
/* freebasic product card: reveal 1s after the section first scrolls into view */
(function(){var sec=document.querySelector('.freebasic-section'),ov=document.querySelector('.fb-overlay');if(!sec||!ov)return;function steps(){setTimeout(function(){ov.classList.add('s1')},1000);setTimeout(function(){ov.classList.add('s2')},2000);setTimeout(function(){ov.classList.add('s3')},2500);setTimeout(function(){ov.classList.add('s4')},3000)}if(!('IntersectionObserver'in window)){ov.classList.add('s1','s2','s3','s4');return}var done=false;var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting&&!done){done=true;io.disconnect();steps()}})},{threshold:.25});io.observe(sec)})();
/* bento cards: on touch (no hover) auto-cycle the image reveal like the reference */
(function(){if(window.matchMedia&&(window.matchMedia('(hover:hover)').matches||window.matchMedia('(prefers-reduced-motion: reduce)').matches))return;var sec=document.querySelector('.bento-sec');if(!sec)return;var cards=sec.querySelectorAll('.bcard');if(!cards.length)return;var i=-1,timer=null;function clear(){for(var k=0;k<cards.length;k++)cards[k].classList.remove('demo-on')}function step(){clear();i=(i+1)%cards.length;cards[i].classList.add('demo-on')}function start(){if(timer)return;step();timer=setInterval(step,1800)}function stop(){if(timer){clearInterval(timer);timer=null}clear()}if(!('IntersectionObserver'in window)){start();return}var io=new IntersectionObserver(function(en){en.forEach(function(x){if(x.isIntersecting){start()}else{stop()}})},{threshold:.3});io.observe(sec)})();
